"use client";
import {useEffect,useState} from "react";
import {campaignSchema,campaignStatus,displayTypes,type Campaign,type CampaignRecord} from "@/lib/campaigns";
import {Field,Notice,api} from "../sales/ui";
import {money} from "@/lib/sales/validation";
type Row=CampaignRecord&{impressions:number;clicks:number;dismissals:number;productViews:number;requests:number;quoteValue:number};
const blank=():Campaign=>campaignSchema.parse({name:"New campaign",headline:"Your campaign headline",types:["hero"]});
const toLocal=(s:string|null)=>{if(!s)return "";const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export default function Campaigns(){
 const[rows,setRows]=useState<Row[]>([]),[data,setData]=useState<Campaign>(blank),[current,setCurrent]=useState<Row|null>(null),[categories,setCategories]=useState<string[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[productSearch,setProductSearch]=useState(""),[products,setProducts]=useState<{code:string;name:string}[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/campaigns",{cache:"no-store"});const result=await r.json();if(!r.ok)throw new Error(result.error);setRows(result.items);setCategories(result.categories);return result.items as Row[]}
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(productSearch.length<2)return;let alive=true;const timer=setTimeout(()=>api(`products?q=${encodeURIComponent(productSearch)}`).then(r=>{if(alive)setProducts(r.items)}).catch(e=>setError(e.message)),250);return()=>{alive=false;clearTimeout(timer)}},[productSearch]);
 function choose(row:Row|null){setCurrent(row);setData(row?row.data:blank());setError("");setNotice("")}
 async function upload(file:File,key:"desktopImage"|"mobileImage"){
  setBusy(true);setError("");try{if(file.size>10000000||!/^image\/(png|jpeg|webp)$/.test(file.type))throw new Error("Choose a PNG, JPEG or WebP under 10 MB.");const bitmap=await createImageBitmap(file);const width=Math.min(bitmap.width,key==="mobileImage"?800:1600);const canvas=document.createElement("canvas");canvas.width=width;canvas.height=Math.round(bitmap.height*width/bitmap.width);const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Image processing unavailable.");ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.82));if(!blob||blob.size>1000000)throw new Error("Image is too large. Please choose a smaller image.");const r=await fetch("/api/admin/campaign-assets",{method:"POST",headers:{"content-type":blob.type},body:blob});const result=await r.json();if(!r.ok)throw new Error(result.error);setData(d=>({...d,[key]:result.url}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function save(){setBusy(true);setError("");try{const parsed=campaignSchema.parse(data);const r=await fetch("/api/admin/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...(current?{id:current.id,version:current.version}:{}),data:parsed})});const result=await r.json();if(!r.ok)throw new Error(result.error);const updated=await load();const row=updated.find(c=>c.id===result.id)!;setCurrent(row);setData(row.data);setNotice("Campaign saved. Scheduling and visibility update automatically; no deployment required.")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="sales-content"><h1>Marketing / Campaigns</h1><Notice error={error} notice={notice}/><div className="campaign-layout"><aside><div className="sales-actions"><button onClick={()=>choose(null)}>New campaign</button></div><Field label="Search campaigns" value={q} onChange={setQ}/><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{["Draft","Disabled","Scheduled","Active","Expired"].map(s=><option key={s}>{s}</option>)}</select></label><div className="campaign-admin-list">{rows.filter(r=>(!q||r.data.name.toLowerCase().includes(q.toLowerCase()))&&(!status||campaignStatus(r.data)===status)).map(r=><button key={r.id} onClick={()=>choose(r)}><span><strong>{r.data.name}</strong><small>{r.data.types.join(" · ")}</small></span><span className="sales-badge">{campaignStatus(r.data)}</span></button>)}</div></aside>
 <form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><section className="sales-panel"><div className="sales-actions"><h2>{current?"Edit campaign":"Create campaign"}</h2><span className="sales-badge">{campaignStatus(data)}</span></div>{current&&<div className="campaign-stats">{[["Impressions",current.impressions],["Clicks",current.clicks],["Dismissals",current.dismissals],["Product views",current.productViews],["Quote requests",current.requests],["Issued quote value",money(current.quoteValue)]].map(([label,value])=><span key={label}>{label}<strong>{value}</strong></span>)}</div>}<div className="sales-form">{([['name','Internal name'],['headline','Headline'],['text','Supporting text'],['ctaLabel','CTA label'],['ctaDestination','CTA destination (catalogue path)']] as const).map(([key,label])=><Field key={key} label={label} value={data[key]} multiline={key==='text'} onChange={v=>setData({...data,[key]:v})}/>)}</div></section>
 <section className="sales-panel"><h2>Campaign images</h2><p className="sales-muted">Images are resized and compressed before upload. Use a landscape desktop image and a compact mobile crop.</p><div className="sales-form">{(["desktopImage","mobileImage"] as const).map(key=><label key={key}>{key==="desktopImage"?"Desktop image":"Mobile image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,key)}}/>{data[key]&&<><img className="campaign-image-preview" src={data[key]} alt="Campaign preview"/><button type="button" className="secondary" onClick={()=>setData({...data,[key]:""})}>Remove image</button></>}</label>)}</div></section>
 <section className="sales-panel"><h2>Where it appears</h2>{displayTypes.map(t=><label className="sales-check" key={t}><input type="checkbox" checked={data.types.includes(t)} onChange={e=>setData({...data,types:e.target.checked?[...data.types,t]:data.types.filter(v=>v!==t)})}/>{({popup:"Popup / modal",announcement:"Announcement bar",hero:"Catalogue hero",product:"Product page promotion"})[t]}</label>)}<label>Target<select value={data.target} onChange={e=>setData({...data,target:e.target.value as Campaign["target"]})}>{Object.entries({all:"Entire catalogue",home:"Catalogue homepage",browse:"Search / browse pages",categories:"Specific categories",products:"Specific products"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{data.target==="categories"&&<label>Categories (select one or more)<select multiple value={data.categories} onChange={e=>setData({...data,categories:Array.from(e.target.selectedOptions,o=>o.value)})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}{data.target==="products"&&<><Field label="Find product" value={productSearch} onChange={setProductSearch}/><div className="campaign-target-products">{data.products.map(code=><button type="button" key={code} className="secondary" onClick={()=>setData({...data,products:data.products.filter(c=>c!==code)})}>{code} ×</button>)}</div>{productSearch.length>=2&&products.map(p=><button type="button" className="secondary" key={p.code} onClick={()=>{setData({...data,products:[...new Set([...data.products,p.code])]});setProductSearch("")}}>{p.code} · {p.name}</button>)}</>}</section>
 <section className="sales-panel"><h2>Schedule & frequency</h2><div className="sales-form"><label>Start (your local time)<input type="datetime-local" value={toLocal(data.startsAt)} onChange={e=>setData({...data,startsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label>End (your local time)<input type="datetime-local" value={toLocal(data.endsAt)} onChange={e=>setData({...data,endsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><Field label="Priority (higher first)" type="number" value={data.priority} onChange={v=>setData({...data,priority:Number(v)})}/><label>Popup frequency<select value={data.frequency} onChange={e=>setData({...data,frequency:e.target.value as Campaign["frequency"]})}><option value="session">Once per session</option><option value="days">Once per X days</option><option value="campaign">Once per campaign</option><option value="visit">Every visit</option></select></label>{data.frequency==="days"&&<Field label="Days between appearances" type="number" value={data.frequencyDays} onChange={v=>setData({...data,frequencyDays:Number(v)})}/>}</div><label className="sales-check"><input type="checkbox" checked={data.published} onChange={e=>setData({...data,published:e.target.checked})}/>Publish (uncheck to keep as draft)</label><label className="sales-check"><input type="checkbox" checked={data.enabled} onChange={e=>setData({...data,enabled:e.target.checked})}/>Enabled</label><p className="sales-muted">Published and enabled campaigns appear only during their schedule. Disable to hide within one minute on already-open pages. New pages reflect changes immediately.</p></section><button>{busy?"Saving…":"Save campaign"}</button></fieldset></form></div></div>
}
