"use client";
import type {ProductPageProduct,ProductPageVariant} from "@/lib/catalogue-product";
import type {QuoteSelection} from "@/lib/quote-request-schema";
export default function ProductOptions({product,variants,value,onChange}:{product:ProductPageProduct;variants:ProductPageVariant[];value:QuoteSelection;onChange:(value:QuoteSelection)=>void}){
 const variant=variants.find(v=>v.code===value.variantCode),methods=[...new Set(product.branding.map(b=>b.method))];
 return <div className="quote-options"><label>Colour / size<select value={value.variantCode} onChange={e=>onChange({...value,variantCode:e.target.value})}><option value="">Help me choose a variant</option>{variants.map(v=><option key={v.code} value={v.code}>{[v.colour,v.size].filter(Boolean).join(" / ")||v.code} · {v.stock===null?"Stock to confirm":`${v.stock} in stock`}</option>)}</select></label>{variant&&<p className="option-stock">{variant.stock===null?"Stock to confirm":""+variant.stock+" available"} for {variant.colour} {variant.size}</p>}
 <fieldset><legend>How many do you need?</legend><div className="quantity-shortcuts">{[25,50,100,250,500].map(n=><button type="button" key={n} aria-pressed={value.quantity===n} onClick={()=>onChange({...value,quantity:n})}>{n}</button>)}<button type="button" aria-pressed={value.quantity===null} onClick={()=>onChange({...value,quantity:null})}>Not sure yet</button></div><label>Custom quantity<input type="number" min="1" max="1000000" step="1" placeholder="Your required quantity" value={value.quantity??""} onChange={e=>onChange({...value,quantity:e.target.value?Number(e.target.value):null})}/></label></fieldset>
 {value.quantity!==null&&variant&&variant.stock!==null&&value.quantity>variant.stock&&<p className="option-stock">Your quantity exceeds current stock. We’ll confirm availability and incoming stock in your quote.</p>}
 <fieldset><legend>Make it yours</legend><div className="branding-choice"><button type="button" aria-pressed={!value.branded} onClick={()=>onChange({...value,branded:false,method:"",position:""})}><strong>Unbranded</strong><span>Plain product</span></button><button type="button" aria-pressed={value.branded} onClick={()=>onChange({...value,branded:true})}><strong>Branded</strong><span>Add my logo / design</span></button></div></fieldset>
 {value.branded&&<div className="branding-fields"><label>Branding method<select value={value.method} onChange={e=>onChange({...value,method:e.target.value,position:product.branding.find(b=>b.method===e.target.value)?.position||""})}><option value="">Let Gentwelve recommend the best method</option>{methods.map(m=><option key={m}>{m}</option>)}</select></label>{value.method&&<label>Position<select value={value.position} onChange={e=>onChange({...value,position:e.target.value})}>{product.branding.filter(b=>b.method===value.method).map(b=><option key={b.code+b.position} value={b.position}>{b.position||"Standard position"}</option>)}</select></label>}<p>Final branding price will be confirmed in your quotation.</p></div>}
 <label>Notes for this product<textarea maxLength={2000} value={value.notes} onChange={e=>onChange({...value,notes:e.target.value})} placeholder="Tell us about your logo, colours or requirements"/></label></div>
}
