import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
import {decimalCents,equalSignature,payfastSignature,ozowHash,ozowResponseOrder} from '../lib/sales/providers/security.ts';
async function adapter(name){const url=new URL(`../lib/sales/providers/${name}.ts`,import.meta.url);const source=(await readFile(url,'utf8')).replace('"./security"',JSON.stringify(new URL('../lib/sales/providers/security.ts',import.meta.url).href));const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return (await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64')))[name]}
test('provider amounts and signatures reject malformed input',()=>{assert.equal(decimalCents('123.45'),12345);assert.equal(decimalCents('0.10'),10);for(const v of ['1e3','-1','1.001','NaN'])assert.throws(()=>decimalCents(v));assert.equal(equalSignature('abcd','abcd'),true);assert.equal(equalSignature('abcd','xyz'),false);assert.equal(payfastSignature({name_first:'A B',amount:'10.00'},'secret phrase'),createHash('md5').update('name_first=A+B&amount=10.00&passphrase=secret+phrase').digest('hex'))});
test('Paystack requires signature and independent API confirmation',async()=>{
 const old=global.fetch;const key=process.env.PAYSTACK_SECRET_KEY;process.env.PAYSTACK_SECRET_KEY='sk_test_fixture';
 try{const p=await adapter('paystack');const raw=JSON.stringify({event:'charge.success',data:{reference:'GT-fixture'}});await assert.rejects(p.verify(raw,new Headers()));let calls=0;global.fetch=async()=>{calls++;return Response.json({status:true,data:{id:42,reference:'GT-fixture',status:'success',amount:10000,currency:'ZAR',domain:'test',paid_at:'2026-09-18T12:00:00Z'}})};const headers=new Headers({'x-paystack-signature':createHmac('sha512','sk_test_fixture').update(raw).digest('hex')});const v=await p.verify(raw,headers);assert.equal(v.amountCents,10000);assert.equal(v.testMode,true);assert.equal(calls,1);global.fetch=async()=>Response.json({status:true,data:{status:'pending'}});await assert.rejects(p.verify(raw,headers));}finally{global.fetch=old;if(key===undefined)delete process.env.PAYSTACK_SECRET_KEY;else process.env.PAYSTACK_SECRET_KEY=key}
});
test('PayFast verifies signature, merchant and server validation',async()=>{
 const old=global.fetch;const saved={...process.env};Object.assign(process.env,{PAYFAST_MERCHANT_ID:'10000100',PAYFAST_PASSPHRASE:'fixture',PAYFAST_SANDBOX:'true'});delete process.env.VERCEL;
 try{const p=await adapter('payfast');const fields={merchant_id:'10000100',m_payment_id:'GT-fixture',pf_payment_id:'123',payment_status:'COMPLETE',amount_gross:'150.50'};fields.signature=payfastSignature(fields,'fixture');const raw=new URLSearchParams(fields).toString();global.fetch=async()=>new Response('VALID');const result=await p.verify(raw,new Headers());assert.equal(result.amountCents,15050);assert.equal(result.testMode,true);await assert.rejects(p.verify(raw.replace('150.50','150.51'),new Headers()));global.fetch=async()=>new Response('INVALID');await assert.rejects(p.verify(raw,new Headers()));}finally{global.fetch=old;for(const k of ['PAYFAST_MERCHANT_ID','PAYFAST_PASSPHRASE','PAYFAST_SANDBOX','VERCEL']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k]}}
});
test('Ozow verifies signed fields against the transaction API',async()=>{
 const old=global.fetch;const saved={...process.env};Object.assign(process.env,{OZOW_SITE_CODE:'fixture-site',OZOW_PRIVATE_KEY:'fixture',OZOW_API_KEY:'fixture-api'});
 try{const p=await adapter('ozow');const fields={SiteCode:'fixture-site',TransactionId:'tx1',TransactionReference:'GT-fixture',Amount:'100.00',Status:'Complete',CurrencyCode:'ZAR',IsTest:'false',StatusMessage:''};fields.Hash=ozowHash(fields,ozowResponseOrder,'fixture');const raw=new URLSearchParams(fields).toString();global.fetch=async()=>Response.json([{TransactionId:'tx1',SiteCode:'fixture-site',TransactionReference:'GT-fixture',Amount:100,Status:'Complete',CurrencyCode:'ZAR'}]);assert.equal((await p.verify(raw,new Headers())).amountCents,10000);await assert.rejects(p.verify(raw.replace('100.00','200.00'),new Headers()));global.fetch=async()=>Response.json([]);await assert.rejects(p.verify(raw,new Headers()));}finally{global.fetch=old;for(const k of ['OZOW_SITE_CODE','OZOW_PRIVATE_KEY','OZOW_API_KEY']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k]}}
});
