"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import type {ProductPageProduct,ProductPageVariant} from "@/lib/catalogue-product";
import {useBasket,BasketLink} from "../components/quote/basket-provider";
import ProductOptions from "../components/quote/product-options";
import {selectionSchema} from "@/lib/quote-request-schema";
import {money} from "@/lib/sales/validation";
type Detail={product:ProductPageProduct;variants:ProductPageVariant[]};
export default function QuotePage(){
 const basket=useBasket(),[products,setProducts]=useState<Record<string,Detail>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[success,setSuccess]=useState<{reference:string;whatsappUrl:string}|null>(null),[form,setForm]=useState({name:"",company:"",email:"",mobile:"",city:"",requiredBy:"",instructions:"",reference:"",website:""}),[file,setFile]=useState<File|null>(null);
 const requestKey=useRef("");const codes=[...new Set(basket.items.map(i=>i.code))].sort().join(",");
 useEffect(()=>{if(!codes)return;const controller=new AbortController();fetch(`/api/quote-products?codes=${encodeURIComponent(codes)}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setProducts(Object.fromEntries(d.products.map((p:Detail)=>[p.product.code,p])))}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[codes]);
 async function submit(){setBusy(true);setError("");try{
  if(!requestKey.current)requestKey.current=crypto.randomUUID();let campaignId=null;try{const c=JSON.parse(localStorage.getItem("gentwelve_campaign_attribution")||"null");if(c&&Date.now()-c.at<30*86400000)campaignId=c.id}catch{}
  const data={...form,requestKey:requestKey.current,campaignId,items:basket.items.map(i=>selectionSchema.parse(Object.fromEntries(Object.keys(selectionSchema.shape).map(k=>[k,i[k as keyof typeof i]]))))};
  const body=new FormData();body.append("data",JSON.stringify(data));if(file)body.append("artwork",file);
  const r=await fetch("/api/quote-requests",{method:"POST",body});const result=await r.json();if(!r.ok)throw new Error(result.error||"Could not send your request.");setSuccess(result);basket.clear();
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="quote-page"><header className="quote-header"><Link href="/"><img src="/gentwelve-web-logo-w.svg" alt="Gentwelve"/></Link><BasketLink/></header><div className="quote-shell"><Link href="/">← Continue shopping</Link><span className="quote-eyebrow">YOUR NEXT BRAND MOMENT</span><h1>Your quote basket</h1><p>Select the products. We’ll take care of the details.</p>{error&&<p className="quote-error" role="alert">{error}</p>}{basket.storageError&&<p role="status">{basket.storageError}</p>}
 {success?<section className="quote-success"><h2>Thank you. Your request is with Gentwelve.</h2><p>Reference <strong>{success.reference}</strong></p><p>Our sales team will review your products, branding and delivery requirements.</p><Link className="quote-primary" href={success.whatsappUrl} target="_blank" rel="noreferrer">Discuss this request on WhatsApp</Link><Link href="/">Continue shopping</Link></section>:!basket.ready?<p>Loading your quote…</p>:!basket.items.length?<section className="quote-empty"><h2>Start with something worth branding.</h2><p>Add a product from the catalogue to begin.</p><Link className="quote-primary" href="/">Explore the catalogue</Link></section>:<div className="quote-layout"><section aria-label="Quote items">{basket.items.map(item=>{const d=products[item.code];return <article className="basket-item" key={item.id}><div className="basket-summary"><img src={item.image} alt=""/><div><small>{item.code}</small><h2>{item.name}</h2><p>{[item.colour,item.size].filter(Boolean).join(" / ")||"Variant to be confirmed"}</p><p>{item.quantity??"Quantity to be confirmed"}{item.quantity?" units":""} · {item.branded?item.method||"Branding advice requested":"Unbranded"}</p>{item.priceCents!==null&&<small>Product from {money(item.priceCents)} each</small>}</div><button type="button" className="quote-remove" onClick={()=>basket.remove(item.id)} aria-label={`Remove ${item.name}`}>Remove</button></div><details><summary>Edit quantity, variant, branding & notes</summary>{d?<ProductOptions product={d.product} variants={d.variants} value={item} onChange={value=>{const v=d.variants.find(v=>v.code===value.variantCode);basket.update(item.id,{...value,colour:v?.colour||"",size:v?.size||"",priceCents:v?.priceCents??d.product.priceCents})}}/>:<p>Product options are unavailable. Remove this item or contact sales if it is no longer in the catalogue.</p>}</details></article>})}<p className="quote-disclaimer">Indicative product pricing only. Final branding price will be confirmed in your quotation. Stock, delivery and VAT where applicable are confirmed by our team.</p><Link href="/">+ Continue shopping</Link></section>
 <section className="quote-customer"><h2>Request your quotation</h2><p>No payment required. Tell us where to send your quote.</p><form onSubmit={e=>{e.preventDefault();void submit()}}><fieldset disabled={busy}>{Object.entries({name:"Your name",company:"Company",email:"Email",mobile:"Mobile / WhatsApp",city:"Delivery suburb / city",requiredBy:"Required-by date",reference:"PO / reference"}).map(([key,label])=><label key={key}>{label}{["name","company","email","mobile"].includes(key)?" *":""}<input required={["name","company","email","mobile"].includes(key)} type={key==="email"?"email":key==="requiredBy"?"date":key==="mobile"?"tel":"text"} maxLength={300} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Additional instructions<textarea maxLength={3000} value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></label><label>Artwork / logo (optional)<input type="file" accept=".pdf,.ai,.eps,.svg,.png,.jpg,.jpeg" onChange={e=>{const f=e.target.files?.[0]||null;if(f&&f.size>3000000){setError("Artwork must be under 3 MB.");e.target.value="";setFile(null)}else{setFile(f);setError("")}}}/><small>One PDF, AI, EPS, SVG, PNG or JPEG, up to 3 MB. Only our sales team can access it.</small></label><label className="quote-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></label><p className="quote-disclaimer">We’ll use these details to respond to your request and arrange your order.</p><button className="quote-primary" disabled={busy}>{busy?"Sending request…":"Request quote"}</button><p className="quote-disclaimer">Prefer WhatsApp? Submit first, then use the WhatsApp link so our team has your full request.</p></fieldset></form></section></div>}</div></main>
}
