"use client";
import {useEffect,useState} from "react";
import type {SalesDocument} from "@/lib/sales/documents";
import DocumentView from "@/app/components/sales/document-view";
import {api,Field,Notice} from "../../ui";
import PaymentPanel from "./payment-panel";
const statuses=["artwork_required","artwork_approval","ready_for_production","in_production","ready_for_dispatch","dispatched","completed"];
type Payload={document:SalesDocument;status:string;paid?:number;payments:{id:string;provider:string;reference:string;provider_reference:string|null;amount_cents:number;status:string;test_mode:boolean;paid_at:string|null}[];related:{id:string;kind:string;number:string;status:string}[];events:{event:string;actor:string;createdAt:string}[]};
export default function Detail({id}:{id:string}){
 const[payload,setPayload]=useState<Payload|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[dueOn,setDueOn]=useState(new Date(Date.now()+30*86400000).toISOString().slice(0,10)),[delivery,setDelivery]=useState({deliveredBy:"",recipientName:"",deliveryNotes:""});
 async function load(){setPayload(await api(`documents/${id}`))}
 useEffect(()=>{let cancelled=false;api(`documents/${id}`).then(r=>{if(!cancelled)setPayload(r)}).catch(e=>setError(e.message));return()=>{cancelled=true}},[id]);
 async function action(action:string,extra:Record<string,unknown>={}){setBusy(true);setError("");try{const result=await api(`documents/${id}`,"POST",{action,...extra});if(result.id&&result.id!==id)window.location.assign(`/admin/sales/documents/${result.id}`);else{await load();setNotice("Saved.")}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!payload)return <div className="sales-content"><Notice error={error}/><p>Loading document…</p></div>;
 const d=payload.document;
 return <div className="sales-content"><a href="/admin/sales">← Sales</a><div className="sales-actions"><h1>{d.number||"Draft quotation"}</h1><span className="sales-badge">{payload.status.replaceAll("_"," ")}</span></div><Notice error={error} notice={notice}/><div className="sales-actions"><a className="sales-button" href={`/api/admin/sales/documents/${id}?format=pdf`}>Download PDF</a>{d.status==="draft"&&<><button disabled={busy} onClick={()=>action("issue")}>{d.kind==="quote"?"Issue / mark sent":"Issue invoice"}</button>{d.kind==="quote"&&<a href={`/admin/sales/new?edit=${id}`}>Edit draft</a>}</>}{d.kind==="quote"&&d.status==="accepted"&&<button disabled={busy} onClick={()=>action("order")}>Create sales order</button>}{d.status!=="cancelled"&&!(["accepted","converted"].includes(d.status)&&d.kind==="quote")&&<button className="secondary" disabled={busy} onClick={()=>{if(window.confirm("Cancel this document? Its history will be preserved."))void action("status",{status:"cancelled",version:d.version})}}>Cancel document</button>}</div>
 {d.kind==="quote"&&d.number&&<section className="sales-panel"><strong>Private customer link</strong><p className="sales-muted">Share this link with the customer. Issuing does not send an email or WhatsApp message automatically.</p><a className="sales-private-link" href={`/q/${d.public_token}`} target="_blank" rel="noreferrer">Open customer quotation</a><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/q/${d.public_token}`);setNotice("Private quotation link copied.")}catch{setError("Copy failed. Open the customer link and copy its address.")}}}>Copy link</button></section>}
 {d.kind==="order"&&d.status!=="cancelled"&&<section className="sales-panel"><h2>Order actions</h2><div className="sales-actions"><label>Production / delivery status<select disabled={busy} value={statuses.includes(d.status)?d.status:""} onChange={e=>action("status",{status:e.target.value,version:d.version})}><option value="">Choose operational status</option>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label></div><div className="sales-form"><Field label="Invoice due date" type="date" value={dueOn} onChange={setDueOn}/></div><div className="sales-actions"><button disabled={busy} onClick={()=>action("invoice",{dueOn})}>Create / open invoice</button></div><details><summary>Generate delivery note</summary><div className="sales-form">{Object.entries({deliveredBy:"Delivered by",recipientName:"Recipient name",deliveryNotes:"Delivery notes"}).map(([key,label])=><Field key={key} label={label} value={delivery[key as keyof typeof delivery]} onChange={v=>setDelivery({...delivery,[key]:v})}/>)}</div><button disabled={busy} onClick={()=>action("delivery",delivery)}>Generate delivery note</button></details></section>}
 {d.kind==="order"&&d.status!=="cancelled"&&<PaymentPanel key={`${id}-${payload.paid}`} token={d.public_token} due={Math.max(0,d.total_cents-(payload.paid||0))} payments={payload.payments||[]} busy={busy} onConfirm={data=>action("eft",{data})}/>}
 <DocumentView document={d} paid={payload.paid||0}/><section className="sales-panel"><h2>Related documents</h2><div className="sales-list">{payload.related.map(r=><a className="sales-row" href={`/admin/sales/documents/${r.id}`} key={r.id}>{r.number||`Draft ${r.kind}`}<span>{r.status}</span></a>)}</div><a href={`/admin/sales?customer=${d.customer_id}`}>Customer history →</a></section><section className="sales-panel"><h2>Activity</h2>{payload.events.map((e,i)=><p key={i}>{e.event.replaceAll("_"," ")} · {e.actor} · {new Date(e.createdAt).toLocaleString("en-ZA")}</p>)}</section></div>;
}
