"use client";
import {useState} from "react";
import {money} from "@/lib/sales/validation";
import {Field} from "../../ui";
type PaymentRow={id:string;provider:string;reference:string;provider_reference:string|null;amount_cents:number;status:string;test_mode:boolean;paid_at:string|null};
export default function PaymentPanel({token,due,payments,onConfirm,busy}:{token:string;due:number;payments:PaymentRow[];onConfirm:(data:Record<string,unknown>)=>Promise<void>;busy:boolean}){
 const[amount,setAmount]=useState(due),[reference,setReference]=useState(""),[receivedOn,setReceivedOn]=useState(new Date().toISOString().slice(0,10)),[confirmed,setConfirmed]=useState(false),[requestId,setRequestId]=useState("");
 return <section className="sales-panel"><h2>Payments</h2><div className="sales-actions"><a className="sales-button" href={`/pay/${token}`} target="_blank" rel="noreferrer">Open payment link</a><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/pay/${token}`)}catch{window.open(`/pay/${token}`,"_blank","noopener,noreferrer")}}}>Copy payment link</button></div><p>Balance due: {money(due)}</p>{due>0&&<details><summary>Record received EFT</summary><p className="sales-muted">Only confirm after verifying the money in Gentwelve’s bank account. A proof-of-payment message alone is not confirmation.</p><div className="sales-form"><Field label="Amount received (R)" type="number" value={amount/100} onChange={v=>{setAmount(Math.round(Number(v)*100));setRequestId("")}}/><Field label="Unique bank receipt / transaction reference" value={reference} onChange={v=>{setReference(v);setRequestId("")}}/><Field label="Date received" type="date" value={receivedOn} onChange={v=>{setReceivedOn(v);setRequestId("")}}/></div><label className="sales-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have verified receipt in the bank account.</label><button disabled={busy||!confirmed||!reference.trim()||amount<=0} onClick={async()=>{const key=requestId||crypto.randomUUID();setRequestId(key);await onConfirm({amountCents:amount,reference,receivedOn,confirmed,requestId:key})}}>Confirm payment received</button></details>}
 <div className="sales-list">{payments.map(p=><div className="sales-row" key={p.id}><div>{p.provider} · {p.status}{p.test_mode?" (TEST — not credited)":""}<small>{p.provider_reference||p.reference}</small><small>{p.paid_at?new Date(p.paid_at).toLocaleDateString("en-ZA"):"Pending confirmation"}</small></div><strong>{money(p.amount_cents)}</strong></div>)}</div></section>;
}
