import type {SalesDocument} from "@/lib/sales/documents";
import {money} from "@/lib/sales/validation";
export default function DocumentView({document:d,paid=0}:{document:SalesDocument;paid?:number}){
 const s=d.snapshot,b=s.business,c=s.customer,delivery=d.kind==="delivery";
 return <article className="sales-document"><header className="sales-document-header"><div><img src={b.logoUrl} alt={b.tradingName||"Gentwelve"}/><h2>{b.legalName||b.tradingName}</h2><pre>{b.address}</pre><p>{b.email} {b.telephone}</p><p>{b.website}</p>{b.registrationNumber&&<p>Registration: {b.registrationNumber}</p>}{b.vatRegistered&&<p>VAT: {b.vatNumber}</p>}</div><div><h1>{{quote:"QUOTATION",order:"SALES ORDER",invoice:"INVOICE",delivery:"DELIVERY NOTE"}[d.kind]}</h1><strong>{d.number||"DRAFT"}</strong><p>Date: {String(d.issued_at||d.created_at).slice(0,10)}</p>{d.expires_on&&<p>Valid until: {String(d.expires_on).slice(0,10)}</p>}{d.due_on&&<p>Due: {String(d.due_on).slice(0,10)}</p>}<p>Reference: {s.reference||"—"}</p>{s.quoteNumber&&<p>Quotation: {s.quoteNumber}</p>}{s.orderNumber&&<p>Sales order: {s.orderNumber}</p>}</div></header>
 <div className="sales-form sales-panel"><div><h3>Customer</h3><strong>{c.name}</strong><p>{c.contactPerson}</p><pre>{delivery?c.deliveryAddress:c.billingAddress}</pre><p>{c.email} {c.mobile||c.telephone}</p>{c.registrationNumber&&<p>Registration: {c.registrationNumber}</p>}{b.vatRegistered&&c.vatNumber&&<p>Customer VAT: {c.vatNumber}</p>}</div><div><h3>Salesperson</h3><p>{s.salesperson.name}</p><p>{s.salesperson.whatsapp}</p>{!delivery&&<><h3>Delivery address</h3><pre>{c.deliveryAddress}</pre></>}</div></div>
 <div className="sales-scroll"><table className="sales-table"><thead><tr><th>Code / Description</th><th>Colour / Size</th><th>Qty</th>{!delivery&&<><th>Unit price</th><th>Discount</th>{b.vatRegistered&&<th>VAT</th>}<th>Total</th></>}</tr></thead><tbody>{s.totals.lines.map((line,i)=><tr key={i}><td><strong>{line.productCode}</strong><p>{line.description}</p>{line.brandingMethod&&<small>Branding: {line.brandingMethod} · {line.brandingPosition}</small>}{!delivery&&(line.brandingCents>0||line.setupCents>0||line.otherCents>0)&&<small>Branding / unit: {money(line.brandingCents)} · Setup: {money(line.setupCents)} · Other: {money(line.otherCents)}</small>}</td><td>{line.colour||"—"} / {line.size||"—"}</td><td>{line.quantity}</td>{!delivery&&<><td>{money(line.unitPriceCents)}</td><td>{line.discountBps/100}%</td>{b.vatRegistered&&<td>{money(line.taxCents)}</td>}<td>{money(line.totalCents)}</td></>}</tr>)}</tbody></table></div>
 {!delivery?<div className="sales-total"><p>Subtotal: {money(s.totals.subtotalCents)}</p>{s.totals.discountCents>0&&<p>Discount: -{money(s.totals.discountCents)}</p>}<p>Delivery: {money(s.totals.deliveryCents)}</p>{b.vatRegistered&&<p>VAT ({b.vatRateBps/100}%): {money(s.totals.taxCents)}</p>}<p>Grand total: {money(s.totals.totalCents)}</p>{["order","invoice"].includes(d.kind)&&<><p>Amount paid: {money(paid)}</p><p>Balance due: {money(Math.max(0,d.total_cents-paid))}</p></>}</div>:<section className="sales-panel"><p>Delivered by: {s.deliveredBy||"________________"}</p><p>Received by / Recipient name: {s.recipientName||"________________"}</p><p>Signature: ____________________</p><p>Date: ____________________</p><pre>{s.deliveryNotes}</pre></section>}
 {!delivery&&b.providers.eft&&b.bank&&<section className="sales-panel"><h3>Payment information</h3><p>{b.bank} · {b.accountName}</p><p>Account: {b.accountNumber} · {b.accountType} · Branch: {b.branchCode}</p><p>Payment reference: {s.orderNumber||d.number||"Provided on sales order"}</p><pre>{b.paymentTerms}</pre></section>}
 {!delivery&&s.notes&&<pre>{s.notes}</pre>}<h3>Terms and conditions</h3><pre>{s.terms||"Please contact us for applicable terms."}</pre></article>;
}
