"use client";
import {useEffect,useState} from "react";
import {calculate,type Line} from "@/lib/sales/calculations";
import {money,type Business} from "@/lib/sales/validation";
import CustomerFields,{emptyCustomer} from "../customers/customer-fields";
import {api,Field,Notice} from "../ui";
const newLine=():Line=>({productCode:"",description:"",colour:"",size:"",unitPriceCents:0,quantity:1,discountBps:0,brandingCents:0,setupCents:0,otherCents:0,taxable:true});
export default function QuoteEditor({customerId:initialCustomer,enquiryId,editId}:{customerId?:string;enquiryId?:string;editId?:string}){
 const[customerId,setCustomerId]=useState(initialCustomer||""),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[customerSearch,setCustomerSearch]=useState(""),[newCustomer,setNewCustomer]=useState(emptyCustomer),[creating,setCreating]=useState(false),[lines,setLines]=useState<Line[]>([newLine()]),[reference,setReference]=useState(""),[expiresOn,setExpiresOn]=useState(""),[delivery,setDelivery]=useState(0),[notes,setNotes]=useState(""),[salespersonId,setSalespersonId]=useState(""),[contacts,setContacts]=useState<{id:string;name:string}[]>([]),[business,setBusiness]=useState<Business|null>(null),[productSearch,setProductSearch]=useState(""),[products,setProducts]=useState<{code:string;name:string;priceCents:number|null}[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;api("settings").then(async s=>{if(cancelled)return;setBusiness(s.data);setContacts(s.contacts);setSalespersonId(s.data.defaultSalespersonId);setExpiresOn(new Date(Date.now()+s.data.quoteValidityDays*86400000).toISOString().slice(0,10));
 if(initialCustomer){const c=await api(`customers?id=${initialCustomer}`);if(!cancelled)setCustomers([{id:c.id,name:c.data.name}])}
 if(enquiryId){const result=await api("enquiries");const enquiry=result.items.find((e:{id:string})=>e.id===enquiryId);if(enquiry&&!cancelled){setNotes(enquiry.details.notes||"");setLines([{...newLine(),productCode:enquiry.details.productCode||"",description:enquiry.details.productCode||"",quantity:Math.max(1,parseInt(enquiry.details.quantity)||1)}]);if(enquiry.customerId)setCustomerId(enquiry.customerId)}}
 if(editId){const {document:d}=await api(`documents/${editId}`);if(cancelled)return;if(d.status!=="draft")throw new Error("Only draft quotations can be edited.");setCustomerId(d.customer_id);setCustomers([{id:d.customer_id,name:d.snapshot.customer.name}]);setLines(d.snapshot.totals.lines.map((r:Line)=>Object.fromEntries(Object.keys(newLine()).map(k=>[k,r[k as keyof Line]]))));setReference(d.snapshot.reference);setNotes(d.snapshot.notes);setDelivery(d.snapshot.totals.deliveryCents);setExpiresOn(String(d.expires_on).slice(0,10));setSalespersonId(d.salesperson_id);setVersion(d.version)}
 }).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[initialCustomer,enquiryId,editId]);
 useEffect(()=>{if(!customerSearch)return;let cancelled=false;const timer=setTimeout(()=>api(`customers?q=${encodeURIComponent(customerSearch)}`).then(r=>{if(!cancelled)setCustomers(r.items)}).catch(e=>setError(e.message)),200);return()=>{cancelled=true;clearTimeout(timer)}},[customerSearch]);
 useEffect(()=>{if(productSearch.length<2)return;let cancelled=false;const timer=setTimeout(()=>api(`products?q=${encodeURIComponent(productSearch)}`).then(r=>{if(!cancelled)setProducts(r.items)}).catch(e=>setError(e.message)),200);return()=>{cancelled=true;clearTimeout(timer)}},[productSearch]);
 function update(i:number,key:keyof Line,value:string|boolean){setLines(rows=>rows.map((r,j)=>j===i?{...r,[key]:typeof r[key]==="number"?Number(value):value}:r))}
 let total=0;try{total=calculate(lines,delivery,business?.vatRegistered||false,business?.vatRateBps||0).totalCents}catch{}
 return <div className="sales-content"><h1>{editId?"Edit draft quotation":"New quotation"}</h1><Notice error={error}/><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const data={...(creating?{newCustomer}:{customerId}),...(enquiryId?{enquiryId}:{}),salespersonId,reference,expiresOn,lines,deliveryCents:delivery,notes};const result=editId?await api(`documents/${editId}`,"POST",{action:"edit",data,version}):await api("documents","POST",data);window.location.assign(`/admin/sales/documents/${result.id}`)}catch(e){setError((e as Error).message);setBusy(false)}}}><fieldset disabled={busy||!business}>
 <section className="sales-panel"><h2>Customer</h2><label className="sales-check"><input type="checkbox" checked={creating} onChange={e=>setCreating(e.target.checked)}/>Create a new customer</label>{creating?<CustomerFields value={newCustomer} onChange={setNewCustomer}/>:<div className="sales-form"><Field label="Find customer" value={customerSearch} onChange={setCustomerSearch}/><label>Selected customer<select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Choose a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>}</section>
 <section className="sales-panel"><div className="sales-form"><Field label="Customer reference" value={reference} onChange={setReference}/><Field label="Expiry date" type="date" required value={expiresOn} onChange={setExpiresOn}/><label>Salesperson<select value={salespersonId} onChange={e=>setSalespersonId(e.target.value)}>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div></section>
 <section className="sales-panel"><h2>Products & charges</h2><Field label="Find catalogue product by name or code" value={productSearch} onChange={setProductSearch}/>{productSearch.length>=2&&<div className="sales-list">{products.map(p=><button type="button" className="sales-row" key={p.code} onClick={()=>{setLines(rows=>[...rows.filter(r=>r.description||r.productCode),{...newLine(),productCode:p.code,description:p.name,unitPriceCents:p.priceCents||0}]);setProductSearch("");setProducts([])}}>{p.code} · {p.name}</button>)}</div>}
 {lines.map((line,i)=><section className="sales-line" key={i}><div className="sales-actions"><strong>Item {i+1}</strong><button type="button" className="secondary" disabled={lines.length===1} onClick={()=>setLines(rows=>rows.filter((_,j)=>j!==i))}>Remove</button></div><div className="sales-form"><Field label="Product code / SKU" value={line.productCode} onChange={v=>update(i,"productCode",v)}/><Field label="Description" required multiline value={line.description} onChange={v=>update(i,"description",v)}/><Field label="Colour" value={line.colour} onChange={v=>update(i,"colour",v)}/><Field label="Size / Variant" value={line.size} onChange={v=>update(i,"size",v)}/><Field label="Quantity" type="number" value={line.quantity} onChange={v=>update(i,"quantity",v)}/>{([["unitPriceCents","Unit selling price (R)"],["brandingCents","Branding per unit (R)"],["setupCents","Branding setup (R)"],["otherCents","Other charge (R)"]] as const).map(([key,label])=><Field key={key} label={label} type="number" value={line[key]/100} onChange={v=>update(i,key,String(Math.round(Number(v)*100)))}/>)}<Field label="Discount (%) on product" type="number" value={line.discountBps/100} onChange={v=>update(i,"discountBps",String(Math.round(Number(v)*100)))}/>{business?.vatRegistered&&<label className="sales-check"><input type="checkbox" checked={line.taxable} onChange={e=>update(i,"taxable",e.target.checked)}/>VAT applies</label>}</div></section>)}<button type="button" className="secondary" onClick={()=>setLines(rows=>[...rows,newLine()])}>Add manual line</button></section>
 <section className="sales-panel"><div className="sales-form"><Field label="Delivery charge (R)" type="number" value={delivery/100} onChange={v=>setDelivery(Math.round(Number(v)*100))}/><Field label="Customer-facing notes" multiline value={notes} onChange={setNotes}/></div><p className="sales-total">Total: {money(total)}</p><p className="sales-muted">{business?.vatRegistered?`VAT rate: ${business.vatRateBps/100}%`:"No VAT charged. Gentwelve is not VAT registered."} Discounts apply to the product price; branding per unit, setup and other charges are additional.</p><button>{busy?"Saving…":"Save draft quotation"}</button></section></fieldset></form></div>;
}
