"use client";
import { useEffect,useState } from "react";
import type { Customer } from "@/lib/sales/validation";
import CustomerFields,{emptyCustomer} from "./customer-fields";
import {api,Notice} from "../ui";
type Row={id:string;name:string;data:Customer;version:number;createdAt:string};
export default function Customers(){
 const[items,setItems]=useState<Row[]>([]),[q,setQ]=useState(""),[page,setPage]=useState(0),[more,setMore]=useState(false),[edit,setEdit]=useState<Row|null>(null),[data,setData]=useState(emptyCustomer),[show,setShow]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>{api(`customers?q=${encodeURIComponent(q)}&page=${page}`).then(result=>{if(!cancelled){setItems(result.items);setMore(result.hasMore)}}).catch(e=>{if(!cancelled)setError(e.message)})},200);return()=>{cancelled=true;clearTimeout(timer)}},[q,page,reload]);
 return <div className="sales-content"><h1>Customers</h1><Notice error={error} notice={notice}/><div className="sales-actions"><input aria-label="Search customers" placeholder="Search company, email or mobile" value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/><button onClick={()=>{setEdit(null);setData(emptyCustomer);setShow(true)}}>New customer</button></div>
 {show&&<form className="sales-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await api("customers",edit?"PUT":"POST",edit?{id:edit.id,version:edit.version,data}:data);setNotice("Customer saved.");setShow(false);setReload(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><CustomerFields value={data} onChange={setData}/><div className="sales-actions"><button>Save customer</button><button type="button" className="secondary" onClick={()=>setShow(false)}>Close</button>{edit&&<a className="sales-button" href={`/admin/sales?customer=${edit.id}`}>Document history</a>}</div></fieldset></form>}
 <div className="sales-list">{items.map(row=><div className="sales-row" key={row.id}><div><strong>{row.name}</strong><small>{row.data.contactPerson} · {row.data.email||row.data.mobile}</small><small>Created {new Date(row.createdAt).toLocaleDateString("en-ZA")}</small></div><div className="sales-actions"><button className="secondary" onClick={()=>{setEdit(row);setData(row.data);setShow(true)}}>Edit</button><a href={`/admin/sales/new?customer=${row.id}`}>Quote</a><a href={`/admin/sales?customer=${row.id}`}>History</a></div></div>)}</div><div className="sales-actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!more} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>;
}
