"use client";
import {useEffect,useState} from "react";
import {gatewayStatus} from "@/lib/sales/gateway-status";
import {defaultBusiness,type Business} from "@/lib/sales/validation";
import {api,Field,Notice} from "../ui";
type Sequence={kind:string;prefix:string;nextNumber:number};
export default function Settings(){
 const[data,setData]=useState<Business>(defaultBusiness),[version,setVersion]=useState(0),[sequences,setSequences]=useState<Sequence[]>([]),[readiness,setReadiness]=useState<Record<string,{configured:boolean;testMode:boolean}>>({}),[contacts,setContacts]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const result=await api("settings");setData(result.data);setVersion(result.version);setSequences(result.sequences);setContacts(result.contacts);setReadiness(result.providerReadiness||{})}
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[]);
 const fields=(mapping:Partial<Record<keyof Business,string>>)=>Object.entries(mapping).map(([key,label])=><Field key={key} label={label} value={String(data[key as keyof Business])} multiline={key==="address"||key.endsWith("Terms")} onChange={value=>setData({...data,[key]:value})}/>);
 return <div className="sales-content"><h1>Business / Documents</h1><Notice error={error} notice={notice}/>{!version?<button onClick={()=>void load().catch(e=>setError(e.message))}>Load settings</button>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");setNotice("");try{await api("settings","PUT",{data,version,sequences});await load();setNotice("Settings saved. Existing issued documents retain their original details.")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}>
 <section className="sales-panel"><h2>Business details</h2><div className="sales-form">{fields({legalName:"Legal / Business Name",tradingName:"Trading Name",registrationNumber:"Registration Number",email:"Email",telephone:"Telephone",whatsapp:"WhatsApp",website:"Website",address:"Business Address"})}<label>Logo (PNG/JPEG, max 500 KB)<input type="file" accept="image/png,image/jpeg" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>500000){setError("Logo must be under 500 KB.");return}const reader=new FileReader();reader.onload=()=>setData({...data,logoUrl:String(reader.result)});reader.readAsDataURL(file)}}/></label><label>Default salesperson<select value={data.defaultSalespersonId} onChange={e=>setData({...data,defaultSalespersonId:e.target.value})}>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><p className="sales-muted">Manage the current salesperson in <a href="/admin/catalogue">WhatsApp / Sales Contact</a>.</p></section>
 <section className="sales-panel"><h2>VAT</h2><label className="sales-check"><input type="checkbox" checked={data.vatRegistered} onChange={e=>setData({...data,vatRegistered:e.target.checked})}/>VAT registered</label><div className="sales-form">{fields({vatNumber:"VAT Number"})}<Field label="VAT Rate (%)" type="number" value={data.vatRateBps/100} onChange={v=>setData({...data,vatRateBps:Math.round(Number(v)*100)})}/></div><p className="sales-muted">When disabled, no VAT is charged and invoices are titled INVOICE.</p></section>
 <section className="sales-panel"><h2>Document defaults</h2><div className="sales-form"><Field label="Quotation validity (days)" type="number" value={data.quoteValidityDays} onChange={v=>setData({...data,quoteValidityDays:Number(v)})}/>{fields({quoteTerms:"Quotation Terms",invoiceTerms:"Invoice Terms",paymentTerms:"Payment Terms",deliveryTerms:"Delivery Note Terms"})}</div><h3>Numbering</h3>{sequences.map((s,i)=><div className="sales-form" key={s.kind}><Field label={`${s.kind} prefix`} value={s.prefix} onChange={v=>setSequences(rows=>rows.map((r,j)=>j===i?{...r,prefix:v}:r))}/><Field label="Next sequence" type="number" value={s.nextNumber} onChange={v=>setSequences(rows=>rows.map((r,j)=>j===i?{...r,nextNumber:Number(v)}:r))}/></div>)}<p className="sales-muted">Sequences may move forward only. Issued numbers never change.</p></section>
 <section className="sales-panel"><h2>Banking / Manual EFT</h2><div className="sales-form">{fields({bank:"Bank",accountName:"Account Name",accountNumber:"Account Number",accountType:"Account Type",branchCode:"Branch Code"})}</div></section>
 <section className="sales-panel"><h2>Payment gateways</h2><p className="sales-muted">Add these variables in Vercel → Project → Settings → Environment Variables, then redeploy. Secrets stay on the server. Enable each method here after setup.</p>{Object.entries({paystack:"Paystack",payfast:"PayFast",ozow:"Ozow",eft:"Manual EFT"}).map(([key,label])=>{const enabled=data.providers[key as keyof Business["providers"]];const configured=key==="eft"?Boolean(data.bank&&data.accountName&&data.accountNumber&&data.branchCode):readiness[key]?.configured;const status=gatewayStatus(enabled,!!configured,readiness[key]?.testMode);return <div className="gateway" key={key}><label className="sales-check"><input type="checkbox" checked={enabled} onChange={e=>setData({...data,providers:{...data.providers,[key]:e.target.checked}})}/><strong>{label}</strong><span className="gateway-status">{status}</span></label>{key==="paystack"&&<><p>Required: <code>PAYSTACK_SECRET_KEY</code>. Use sk_test_ for testing or sk_live_ for production.</p><p>Set the Paystack dashboard webhook to <code>{typeof window!=="undefined"?window.location.origin:""}/api/payments/webhooks/paystack</code>.</p></>}{key==="payfast"&&<><p>Required: <code>PAYFAST_MERCHANT_ID</code>, <code>PAYFAST_MERCHANT_KEY</code>, <code>PAYFAST_PASSPHRASE</code>, <code>PAYFAST_SANDBOX</code> (true for test, false for live).</p><p>Enable Onsite Payments in PayFast. Set the same passphrase in its dashboard. ITN URL is sent securely when checkout starts.</p></>}{key==="ozow"&&<><p>Required: <code>OZOW_SITE_CODE</code>, <code>OZOW_PRIVATE_KEY</code>, <code>OZOW_API_KEY</code>, <code>OZOW_TEST_MODE</code> (true for test, false for live).</p><p>Approve your production domain with Ozow. Callback URLs are supplied at checkout. Test transactions never credit an order.</p></>}{key==="eft"&&<p>Complete bank, account name, account number and branch code above. Confirm receipts against your bank statement in the order’s payment panel.</p>}</div>})}<p className="sales-muted">Set NEXT_PUBLIC_SITE_URL to https://catalogue.gentwelve.com. Browser return URLs never mark a payment as paid; signed callbacks and provider verification are required.</p></section><button>{busy?"Saving…":"Save settings"}</button></fieldset></form>}</div>;
}
