"use client";

import { useEffect,useState } from "react";
import { ArrowLeft,Check,Flame,LoaderCircle,Search,Sparkles,Star,X } from "lucide-react";

import SalesContactSettings from "./sales-contact";

type Product={id:number;code:string;name:string;category:string|null;brand:string|null;image:string|null;priceCents:number|null;minimumQuantity:number|null;curated:number;featured:number;trending:number;newArrival:number;displayPriority:number;stock:number;eligible:number};
type Payload={products:Product[];categories:string[];total:number;eligible:number;page:number;pageSize:number;hasMore:boolean;error?:string};
type SyncRun={status:string;finishedAt?:string|null};
type SyncOverview={runs:{products?:SyncRun|null;prices?:SyncRun|null;stock?:SyncRun|null}};
const freshness=(run?:SyncRun|null)=>run?.finishedAt?new Date(run.finishedAt).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short"}):"Not completed";

export default function CatalogueReview(){
 const[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<string[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("draft"),[category,setCategory]=useState(""),[placement,setPlacement]=useState(""),[sync,setSync]=useState<SyncOverview|null>(null),[total,setTotal]=useState(0),[eligible,setEligible]=useState(0),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[saving,setSaving]=useState<number|null>(null),[bulkSaving,setBulkSaving]=useState(false),[reloadKey,setReloadKey]=useState(0),[notice,setNotice]=useState(""),[error,setError]=useState("");

 useEffect(()=>{fetch("/api/admin/sync",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(payload=>{if(payload)setSync(payload as SyncOverview)}).catch(()=>{})},[]);

 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({status,page:"0"});if(query)params.set("q",query);if(category)params.set("category",category);if(placement)params.set("placement",placement);const response=await fetch(`/api/admin/catalogue?${params}`,{cache:"no-store",signal:controller.signal});const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error||"Could not load the catalogue.");setProducts(payload.products);setCategories(payload.categories);setTotal(payload.total);setEligible(payload.eligible);setPage(payload.page);setHasMore(payload.hasMore)}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Could not load the catalogue.")}finally{setLoading(false)}},250);return()=>{controller.abort();window.clearTimeout(timer)}},[query,status,category,placement,reloadKey]);

 async function loadMore(){if(loadingMore||!hasMore)return;setLoadingMore(true);setError("");try{const nextPage=page+1;const params=new URLSearchParams({status,page:String(nextPage)});if(query)params.set("q",query);if(category)params.set("category",category);if(placement)params.set("placement",placement);const response=await fetch(`/api/admin/catalogue?${params}`,{cache:"no-store"});const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error||"Could not load more products.");setProducts(previous=>[...previous,...payload.products.filter(product=>!previous.some(item=>item.id===product.id))]);setPage(payload.page);setHasMore(payload.hasMore);setTotal(payload.total)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load more products.")}finally{setLoadingMore(false)}}

 async function curate(product:Product){setSaving(product.id);setError("");try{const curated=!Boolean(product.curated);const response=await fetch("/api/admin/catalogue",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:product.id,curated})});if(!response.ok)throw new Error("Could not update this product.");setProducts(previous=>status==="all"?previous.map(item=>item.id===product.id?{...item,curated:curated?1:0}:item):previous.filter(item=>item.id!==product.id))}catch(reason){setError(reason instanceof Error?reason.message:"Could not update this product.")}finally{setSaving(null)}}

 async function merchandise(product:Product,change:Partial<Pick<Product,"featured"|"trending"|"newArrival"|"displayPriority">>){setSaving(product.id);setError("");try{const payload={id:product.id,...Object.fromEntries(Object.entries(change).map(([key,value])=>[key,typeof value==="number"&&key!=="displayPriority"?Boolean(value):value]))};const response=await fetch("/api/admin/catalogue",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("Could not update product placement.");setProducts(previous=>previous.map(item=>item.id===product.id?{...item,...change}:item))}catch(reason){setError(reason instanceof Error?reason.message:"Could not update product placement.")}finally{setSaving(null)}}

 async function publishAll(){if(!eligible)return;if(!window.confirm(`Publish all ${eligible.toLocaleString()} eligible products at once? Products without an image, price, category or available stock will remain hidden.`))return;setBulkSaving(true);setError("");setNotice("");try{const response=await fetch("/api/admin/catalogue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publish_all_eligible",confirmed:true})});const payload=await response.json() as {published?:number;error?:string};if(!response.ok)throw new Error(payload.error||"Could not publish the catalogue.");setNotice(`${Number(payload.published||0).toLocaleString()} products published.`);setStatus("published");setReloadKey(value=>value+1)}catch(reason){setError(reason instanceof Error?reason.message:"Could not publish the catalogue.")}finally{setBulkSaving(false)}}

 return <section className="review-shell">
  <header className="review-header"><div><nav className="review-nav"><a href="/admin"><ArrowLeft/> Data control</a><a href="/admin/analytics">Enquiry intelligence →</a></nav><span className="review-kicker">CURATION PHASE</span><h1>Control what goes live.</h1><p>Browse the entire imported catalogue. Products missing an image, price, category or available stock remain safely unpublished.</p></div><div className="review-actions"><div className="review-stat"><strong>{total.toLocaleString()}</strong><span>products in this view</span></div><button className="bulk-publish" onClick={publishAll} disabled={bulkSaving||!eligible}>{bulkSaving?<LoaderCircle className="spin"/>:<Check/>}{bulkSaving?"Publishing…":`Publish all ${eligible.toLocaleString()}`}</button></div></header>
  <SalesContactSettings/>
  <div className="sync-health"><div><small>Products updated</small><strong>{freshness(sync?.runs.products)}</strong></div><div><small>Prices updated</small><strong>{freshness(sync?.runs.prices)}</strong></div><div><small>Stock updated</small><strong>{freshness(sync?.runs.stock)}</strong></div><a href="/admin">Run catalogue update</a></div>
  <div className="review-controls"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name, code or brand"/></label><select value={category} onChange={event=>setCategory(event.target.value)}><option value="">All categories</option>{categories.map(item=><option key={item}>{item}</option>)}</select><select value={placement} onChange={event=>setPlacement(event.target.value)}><option value="">All placements</option><option value="featured">Featured</option><option value="trending">Trending</option><option value="new">New arrivals</option></select><div className="review-tabs">{[["draft","To review"],["published","Published"],["all","All"]].map(([value,label])=><button key={value} className={status===value?"active":""} onClick={()=>setStatus(value)}>{label}</button>)}</div></div>
  {error&&<div className="review-error"><X/>{error}</div>}
  {notice&&<div className="review-notice"><Check/>{notice}</div>}
  {loading?<div className="review-loading"><LoaderCircle className="spin"/>Loading products…</div>:products.length?<><div className="review-grid">{products.map(product=><article className={`review-card${product.eligible?"":" not-ready"}`} key={product.id}><div className="review-image">{product.image?<img src={product.image} alt={product.name}/>:<div className="missing-image">No image</div>}<span>{product.category||"Uncategorised"}</span></div><div className="review-copy"><small>{product.brand||"Gentwelve selection"} · {product.code}</small><h2>{product.name}</h2><div className="review-meta"><span><b>{product.priceCents!==null?`R${Math.ceil(product.priceCents/100).toLocaleString()}`:"No price"}</b>{product.priceCents!==null?"from":"not ready"}</span><span><b>{Number(product.stock).toLocaleString()}</b> stock</span></div><div className="merch-controls"><button className={product.featured?"active":""} onClick={()=>merchandise(product,{featured:product.featured?0:1})} disabled={saving===product.id}><Star/>Featured</button><button className={product.trending?"active":""} onClick={()=>merchandise(product,{trending:product.trending?0:1})} disabled={saving===product.id}><Flame/>Trending</button><button className={product.newArrival?"active":""} onClick={()=>merchandise(product,{newArrival:product.newArrival?0:1})} disabled={saving===product.id}><Sparkles/>New</button><label>Priority<select value={product.displayPriority||0} onChange={event=>merchandise(product,{displayPriority:Number(event.target.value)})} disabled={saving===product.id}>{[0,10,25,50,75,100].map(value=><option key={value} value={value}>{value}</option>)}</select></label></div><button className={product.curated?"published":""} disabled={saving===product.id||(!product.eligible&&!product.curated)} onClick={()=>curate(product)}>{saving===product.id?<LoaderCircle className="spin"/>:product.curated?<X/>:<Check/>}{product.curated?"Remove from site":product.eligible?"Publish product":"Not ready"}</button></div></article>)}</div><div className="review-pagination"><span>Showing <b>{products.length.toLocaleString()}</b> of <b>{total.toLocaleString()}</b> matching products</span>{hasMore&&<button onClick={loadMore} disabled={loadingMore}>{loadingMore?<LoaderCircle className="spin"/>:null}{loadingMore?"Loading…":"Load 60 more"}</button>}</div></>:<div className="review-empty"><h2>No products match.</h2><p>Change the search, category or review status.</p></div>}
 </section>;
}
