"use client";
import {useEffect,useState} from "react";
import {money} from "@/lib/sales/validation";
import {api,Field,Notice} from "./ui";
type Row={id:string;number:string|null;kind:string;status:string;customerName:string;total_cents:number;created_at:string};
type Stats={counts:{kind:string;status:string;count:number;value:number}[];month:{kind:string;count:number;value:number}[];enquiries:number;outstanding?:number;paidOrders?:number;awaitingPayment?:number;outstandingInvoices?:number};
type CustomerTotals={orders:number;value:number;paid:number;balance:number};
type Enquiry={id:string;contactName:string;source:string;status:string;details:{notes?:string;productCode?:string}};
export default function Dashboard({initial}:{initial:{customer?:string;kind?:string;status?:string}}){
 const[customerTotals,setCustomerTotals]=useState<CustomerTotals|null>(null);
 const[rows,setRows]=useState<Row[]>([]),[stats,setStats]=useState<Stats|null>(null),[enquiries,setEnquiries]=useState<Enquiry[]>([]),[q,setQ]=useState(""),[kind,setKind]=useState(initial.kind||""),[status,setStatus]=useState(initial.status||""),[page,setPage]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(""),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[enquiry,setEnquiry]=useState({contactName:"",source:"whatsapp",productCode:"",quantity:"",branding:"",notes:""});
 useEffect(()=>{let cancelled=false;Promise.all([api("dashboard"),api("enquiries")]).then(([s,e])=>{if(!cancelled){setStats(s);setEnquiries(e.items)}}).catch(e=>setError(e.message));return()=>{cancelled=true}},[reload]);
 useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>{const params=new URLSearchParams({q,kind,status,page:String(page)});if(initial.customer)params.set("customer",initial.customer);api(`documents?${params}`).then(r=>{if(!cancelled){setRows(r.items);setMore(r.hasMore)}}).catch(e=>setError(e.message))},150);return()=>{cancelled=true;clearTimeout(timer)}},[q,kind,status,page,initial.customer,reload]);
 useEffect(()=>{if(!initial.customer)return;let cancelled=false;api(`dashboard?customer=${initial.customer}`).then(r=>{if(!cancelled)setCustomerTotals(r)}).catch(e=>setError(e.message));return()=>{cancelled=true}},[initial.customer,reload]);
 const count=(kind:string,status:string)=>stats?.counts.find(r=>r.kind===kind&&r.status===status)?.count||0;
 return <div className="sales-content"><h1>{initial.customer?"Customer document history":"Sales"}</h1><Notice error={error}/><div className="sales-actions"><a className="sales-button" href={`/admin/sales/new${initial.customer?`?customer=${initial.customer}`:""}`}>New quotation</a><a href="/admin/sales/customers">Customers</a></div>
 {initial.customer&&customerTotals&&<div className="sales-metrics"><div>Orders<strong>{customerTotals.orders}</strong></div><div>Total order value<strong>{money(customerTotals.value)}</strong></div><div>Payments received<strong>{money(customerTotals.paid)}</strong></div><div>Outstanding balance<strong>{money(customerTotals.balance)}</strong></div></div>}
 {!initial.customer&&<><div className="sales-metrics"><div>New enquiries<strong>{stats?.enquiries||0}</strong></div>{[["quote","draft","Quotes draft"],["quote","sent","Quotes sent"],["quote","accepted","Quotes accepted"],["order","pending_payment","Awaiting payment"],["order","paid","Paid orders"],["order","in_production","In production"],["order","ready_for_dispatch","Ready for dispatch"],["order","completed","Completed orders"]].map(([k,s,label])=><a href={`/admin/sales?kind=${k}&status=${s}`} key={label}>{label}<strong>{k==="order"&&s==="paid"?stats?.paidOrders||0:k==="order"&&s==="pending_payment"?stats?.awaitingPayment||0:count(k,s)}</strong></a>)}</div><div className="sales-metrics"><div>Quotes this month<strong>{stats?.month.find(r=>r.kind==="quote")?.count||0}</strong></div><div>Accepted quote value<strong>{money((stats?.counts||[]).filter(r=>r.kind==="quote"&&["accepted","converted"].includes(r.status)).reduce((n,r)=>n+r.value,0))}</strong></div><div>Sales this month<strong>{money(stats?.month.find(r=>r.kind==="order")?.value||0)}</strong></div><div>Outstanding invoices ({stats?.outstandingInvoices||0})<strong>{money(stats?.outstanding||0)}</strong></div></div>
 <details className="sales-panel"><summary>Record a WhatsApp / manual enquiry</summary><p className="sales-muted">Enter enquiries received from customers. WhatsApp messages are not read automatically.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await api("enquiries","POST",enquiry);setEnquiry({contactName:"",source:"whatsapp",productCode:"",quantity:"",branding:"",notes:""});setReload(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="sales-form">{Object.entries({contactName:"Customer / Contact",productCode:"Product code",quantity:"Quantity",branding:"Branding",notes:"Enquiry details"}).map(([key,label])=><Field key={key} label={label} multiline={key==="notes"} value={enquiry[key as keyof typeof enquiry]} onChange={v=>setEnquiry({...enquiry,[key]:v})}/>)}</div><button disabled={busy}>Save enquiry</button></form></details><details className="sales-panel"><summary>Enquiries ({enquiries.length} recent)</summary>{enquiries.map(e=><div className="sales-row" key={e.id}><div>{e.contactName||"Product enquiry"}<small>{e.details.productCode} · {e.details.notes}</small><span className="sales-badge">{e.status}</span></div><a href={`/admin/sales/new?enquiry=${e.id}`}>Prepare quote →</a></div>)}</details></>}
 <section className="sales-panel"><h2>Documents</h2><div className="sales-form"><Field label="Search number or customer" value={q} onChange={v=>{setQ(v);setPage(0)}}/><label>Document type<select value={kind} onChange={e=>{setKind(e.target.value);setStatus("");setPage(0)}}><option value="">All documents</option>{["quote","order","invoice","delivery"].map(k=><option key={k}>{k}</option>)}</select></label></div>{status&&<button className="secondary" onClick={()=>setStatus("")}>Clear status: {status}</button>}<div className="sales-list">{rows.map(r=><a className="sales-row" href={`/admin/sales/documents/${r.id}`} key={r.id}><div><strong>{r.number||`Draft ${r.kind}`}</strong><small>{r.customerName} · {new Date(r.created_at).toLocaleDateString("en-ZA")}</small></div><div><span className="sales-badge">{r.status.replaceAll("_"," ")}</span>{r.kind!=="delivery"&&<small>{money(r.total_cents)}</small>}</div></a>)}</div><div className="sales-actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!more} onClick={()=>setPage(p=>p+1)}>Next</button></div></section></div>;
}
